export type BranchBaseRow = {
  name: string;
  invoices: number;
  discInv: number;
  discRate: number;
  noDiscInv: number;
  avgDisc: number;
  discSales: number;
  discVol: number;
  netSales: number;
  appDisc: number;
  utilRate: number;
  avgDiscRate: number;
};
type BranchProductRow = BranchBaseRow;
type BranchSubRow = BranchBaseRow & { products: BranchProductRow[] };
type BranchRow = BranchBaseRow & { subs?: BranchSubRow[] };

export const branches: BranchRow[] = [
  {
    name: "عمّان",
    invoices: 79.0,
    discInv: 38,
    discRate: 68.0,
    noDiscInv: 40,
    avgDisc: 0,
    discSales: 0,
    discVol: 43,
    netSales: 0,
    appDisc: 0.3,
    utilRate: 0.0,
    avgDiscRate: 0.0,
    subs: [
      {
        name: "منتجات غذائية",
        invoices: 42,
        discInv: 22,
        discRate: 52.38,
        noDiscInv: 20,
        avgDisc: 0.15,
        discSales: 0,
        discVol: 24,
        netSales: 0,
        appDisc: 0.15,
        utilRate: 0.0,
        avgDiscRate: 0.0,
        products: [
          {
            name: "أرز عنبر 5كجم",
            invoices: 18,
            discInv: 10,
            discRate: 55.56,
            noDiscInv: 8,
            avgDisc: 0.1,
            discSales: 0,
            discVol: 12,
            netSales: 0,
            appDisc: 0.1,
            utilRate: 0.0,
            avgDiscRate: 0.0,
          },
          {
            name: "زيت نباتي 1.8L",
            invoices: 14,
            discInv: 7,
            discRate: 50.0,
            noDiscInv: 7,
            avgDisc: 0.05,
            discSales: 0,
            discVol: 7,
            netSales: 0,
            appDisc: 0.05,
            utilRate: 0.0,
            avgDiscRate: 0.0,
          },
          {
            name: "سكر أبيض 2كجم",
            invoices: 10,
            discInv: 5,
            discRate: 50.0,
            noDiscInv: 5,
            avgDisc: 0.0,
            discSales: 0,
            discVol: 5,
            netSales: 0,
            appDisc: 0.0,
            utilRate: 0.0,
            avgDiscRate: 0.0,
          },
        ],
      },
      {
        name: "مستلزمات منزلية",
        invoices: 22,
        discInv: 10,
        discRate: 45.45,
        noDiscInv: 12,
        avgDisc: 0.1,
        discSales: 0,
        discVol: 12,
        netSales: 0,
        appDisc: 0.1,
        utilRate: 0.0,
        avgDiscRate: 0.0,
        products: [
          {
            name: "منظف أريال مسحوق",
            invoices: 12,
            discInv: 6,
            discRate: 50.0,
            noDiscInv: 6,
            avgDisc: 0.05,
            discSales: 0,
            discVol: 7,
            netSales: 0,
            appDisc: 0.05,
            utilRate: 0.0,
            avgDiscRate: 0.0,
          },
          {
            name: "صابون صحون فيري",
            invoices: 10,
            discInv: 4,
            discRate: 40.0,
            noDiscInv: 6,
            avgDisc: 0.05,
            discSales: 0,
            discVol: 5,
            netSales: 0,
            appDisc: 0.05,
            utilRate: 0.0,
            avgDiscRate: 0.0,
          },
        ],
      },
      {
        name: "العناية الشخصية",
        invoices: 15,
        discInv: 6,
        discRate: 40.0,
        noDiscInv: 9,
        avgDisc: 0.05,
        discSales: 0,
        discVol: 7,
        netSales: 0,
        appDisc: 0.05,
        utilRate: 0.0,
        avgDiscRate: 0.0,
        products: [
          {
            name: "شامبو هيد آند شولدرز",
            invoices: 8,
            discInv: 3,
            discRate: 37.5,
            noDiscInv: 5,
            avgDisc: 0.03,
            discSales: 0,
            discVol: 4,
            netSales: 0,
            appDisc: 0.03,
            utilRate: 0.0,
            avgDiscRate: 0.0,
          },
          {
            name: "كريم نيفيا للجسم",
            invoices: 7,
            discInv: 3,
            discRate: 42.86,
            noDiscInv: 4,
            avgDisc: 0.02,
            discSales: 0,
            discVol: 3,
            netSales: 0,
            appDisc: 0.02,
            utilRate: 0.0,
            avgDiscRate: 0.0,
          },
        ],
      },
    ],
  },
  {
    name: "الكرك",
    invoices: 1.0,
    discInv: 1,
    discRate: 90.0,
    noDiscInv: 0,
    avgDisc: 1.9,
    discSales: 1,
    discVol: 1,
    netSales: 1,
    appDisc: 1.9,
    utilRate: 4.0,
    avgDiscRate: 4.4,
    subs: [
      {
        name: "منتجات غذائية",
        invoices: 1,
        discInv: 1,
        discRate: 100.0,
        noDiscInv: 0,
        avgDisc: 1.9,
        discSales: 1,
        discVol: 1,
        netSales: 1,
        appDisc: 1.9,
        utilRate: 4.0,
        avgDiscRate: 4.4,
        products: [
          {
            name: "أرز عنبر 5كجم",
            invoices: 1,
            discInv: 1,
            discRate: 100.0,
            noDiscInv: 0,
            avgDisc: 1.9,
            discSales: 1,
            discVol: 1,
            netSales: 1,
            appDisc: 1.9,
            utilRate: 4.0,
            avgDiscRate: 4.4,
          },
        ],
      },
    ],
  },
  {
    name: "المفرق",
    invoices: 1.0,
    discInv: 1,
    discRate: 80.0,
    noDiscInv: 0,
    avgDisc: 1.3,
    discSales: 0,
    discVol: 1,
    netSales: 0,
    appDisc: 1.3,
    utilRate: 3.0,
    avgDiscRate: 3.0,
    subs: [
      {
        name: "فرفاشية",
        invoices: 1,
        discInv: 1,
        discRate: 80.0,
        noDiscInv: 0,
        avgDisc: 1.3,
        discSales: 0,
        discVol: 1,
        netSales: 0,
        appDisc: 1.3,
        utilRate: 3.0,
        avgDiscRate: 3.0,
        products: [
          {
            name: "حلوى شوكولاته مكس",
            invoices: 1,
            discInv: 1,
            discRate: 80.0,
            noDiscInv: 0,
            avgDisc: 1.3,
            discSales: 0,
            discVol: 1,
            netSales: 0,
            appDisc: 1.3,
            utilRate: 3.0,
            avgDiscRate: 3.0,
          },
        ],
      },
    ],
  },
  {
    name: "اربد",
    invoices: 4.0,
    discInv: 1,
    discRate: 60.0,
    noDiscInv: 3,
    avgDisc: 0.5,
    discSales: 0,
    discVol: 1,
    netSales: 0,
    appDisc: 0.5,
    utilRate: 4.0,
    avgDiscRate: 0.46,
    subs: [
      {
        name: "مسطحات غذائية",
        invoices: 2,
        discInv: 1,
        discRate: 50.0,
        noDiscInv: 1,
        avgDisc: 0.3,
        discSales: 0,
        discVol: 1,
        netSales: 0,
        appDisc: 0.3,
        utilRate: 2.0,
        avgDiscRate: 0.3,
        products: [
          {
            name: "عصير مانجو 1L",
            invoices: 2,
            discInv: 1,
            discRate: 50.0,
            noDiscInv: 1,
            avgDisc: 0.3,
            discSales: 0,
            discVol: 1,
            netSales: 0,
            appDisc: 0.3,
            utilRate: 2.0,
            avgDiscRate: 0.3,
          },
        ],
      },
      {
        name: "منتجات غذائية",
        invoices: 2,
        discInv: 0,
        discRate: 0.0,
        noDiscInv: 2,
        avgDisc: 0.2,
        discSales: 0,
        discVol: 0,
        netSales: 0,
        appDisc: 0.2,
        utilRate: 2.0,
        avgDiscRate: 0.16,
        products: [
          {
            name: "شاي ليبتون 100كيس",
            invoices: 2,
            discInv: 0,
            discRate: 0.0,
            noDiscInv: 2,
            avgDisc: 0.2,
            discSales: 0,
            discVol: 0,
            netSales: 0,
            appDisc: 0.2,
            utilRate: 2.0,
            avgDiscRate: 0.16,
          },
        ],
      },
    ],
  },
  {
    name: "الزرقاء",
    invoices: 9.0,
    discInv: 2,
    discRate: 50.0,
    noDiscInv: 7,
    avgDisc: 0.8,
    discSales: 1,
    discVol: 2,
    netSales: 1,
    appDisc: 0.8,
    utilRate: 0.0,
    avgDiscRate: 0.0,
    subs: [
      {
        name: "العناية الشخصية",
        invoices: 5,
        discInv: 1,
        discRate: 20.0,
        noDiscInv: 4,
        avgDisc: 0.4,
        discSales: 0,
        discVol: 1,
        netSales: 0,
        appDisc: 0.4,
        utilRate: 0.0,
        avgDiscRate: 0.0,
        products: [
          {
            name: "معجون أسنان كولجيت",
            invoices: 5,
            discInv: 1,
            discRate: 20.0,
            noDiscInv: 4,
            avgDisc: 0.4,
            discSales: 0,
            discVol: 1,
            netSales: 0,
            appDisc: 0.4,
            utilRate: 0.0,
            avgDiscRate: 0.0,
          },
        ],
      },
      {
        name: "مستلزمات الأطفال",
        invoices: 4,
        discInv: 1,
        discRate: 25.0,
        noDiscInv: 3,
        avgDisc: 0.4,
        discSales: 1,
        discVol: 1,
        netSales: 1,
        appDisc: 0.4,
        utilRate: 0.0,
        avgDiscRate: 0.0,
        products: [
          {
            name: "حفاضات بامبرز",
            invoices: 4,
            discInv: 1,
            discRate: 25.0,
            noDiscInv: 3,
            avgDisc: 0.4,
            discSales: 1,
            discVol: 1,
            netSales: 1,
            appDisc: 0.4,
            utilRate: 0.0,
            avgDiscRate: 0.0,
          },
        ],
      },
    ],
  },
  {
    name: "الإجمالي",
    invoices: 79.0,
    discInv: 38,
    discRate: 68.0,
    noDiscInv: 40,
    avgDisc: 0.94,
    discSales: 2,
    discVol: 43,
    netSales: 2,
    appDisc: 4.8,
    utilRate: 4.0,
    avgDiscRate: 4.45,
  },
];
