export const categories = [
  {
    name: "أجهزة والكترونيات",
    withMargin: 72.73,
    withSales: 0.09,
    noMargin: 57.21,
    noSales: 0.09,
    products: [
      {
        name: 'شاشة سامسونج 32"',
        withMargin: 75.1,
        withSales: 0.04,
        noMargin: 58.2,
        noSales: 0.04,
      },
      {
        name: "مكيف سبليت 1.5طن",
        withMargin: 69.5,
        withSales: 0.03,
        noMargin: 55.8,
        noSales: 0.03,
      },
      {
        name: "طباعة ليزر HP",
        withMargin: 73.8,
        withSales: 0.02,
        noMargin: 57.6,
        noSales: 0.02,
      },
    ],
  },
  {
    name: "العناية الشخصية",
    withMargin: 26.19,
    withSales: 1.06,
    noMargin: 22.11,
    noSales: 0.59,
    products: [
      {
        name: "شامبو هيد آند شولدرز",
        withMargin: 28.4,
        withSales: 0.35,
        noMargin: 23.1,
        noSales: 0.2,
      },
      {
        name: "كريم نيفيا للجسم",
        withMargin: 24.8,
        withSales: 0.42,
        noMargin: 21.3,
        noSales: 0.22,
      },
      {
        name: "معجون أسنان كولجيت",
        withMargin: 25.3,
        withSales: 0.29,
        noMargin: 21.9,
        noSales: 0.17,
      },
    ],
  },
  {
    name: "غير مصنف",
    withMargin: 30.25,
    withSales: 0.25,
    noMargin: 13.11,
    noSales: 0.16,
    products: [
      {
        name: "منتج متنوع أ",
        withMargin: 32.1,
        withSales: 0.12,
        noMargin: 14.2,
        noSales: 0.08,
      },
      {
        name: "منتج متنوع ب",
        withMargin: 28.4,
        withSales: 0.13,
        noMargin: 12.0,
        noSales: 0.08,
      },
    ],
  },
  {
    name: "فرفاشية",
    withMargin: 72.4,
    withSales: 1.42,
    noMargin: 44.64,
    noSales: 2.17,
    products: [
      {
        name: "مثلجات كيه دي دي",
        withMargin: 74.2,
        withSales: 0.55,
        noMargin: 45.8,
        noSales: 0.88,
      },
      {
        name: "حلوى شوكولاته مكس",
        withMargin: 70.8,
        withSales: 0.52,
        noMargin: 43.4,
        noSales: 0.82,
      },
      {
        name: "سناكس متنوعة",
        withMargin: 72.2,
        withSales: 0.35,
        noMargin: 44.7,
        noSales: 0.47,
      },
    ],
  },
  {
    name: "مستلزمات الأطفال",
    withMargin: 22.63,
    withSales: 0.05,
    noMargin: 13.52,
    noSales: 0.17,
    products: [
      {
        name: "حفاضات بامبرز",
        withMargin: 23.8,
        withSales: 0.02,
        noMargin: 14.1,
        noSales: 0.07,
      },
      {
        name: "مناشف رطبة للأطفال",
        withMargin: 21.4,
        withSales: 0.03,
        noMargin: 12.9,
        noSales: 0.1,
      },
    ],
  },
  {
    name: "مستلزمات منزلية",
    withMargin: 38.03,
    withSales: 0.52,
    noMargin: 24.17,
    noSales: 0.08,
    products: [
      {
        name: "منظف أريال مسحوق",
        withMargin: 39.2,
        withSales: 0.2,
        noMargin: 25.4,
        noSales: 0.03,
      },
      {
        name: "صابون صحون فيري",
        withMargin: 37.5,
        withSales: 0.18,
        noMargin: 23.8,
        noSales: 0.03,
      },
      {
        name: "ليف مطبخ",
        withMargin: 37.4,
        withSales: 0.14,
        noMargin: 23.3,
        noSales: 0.02,
      },
    ],
  },
  {
    name: "منتجات ورقية",
    withMargin: 44.55,
    withSales: 0.4,
    noMargin: 41.39,
    noSales: 0.39,
    products: [
      {
        name: "مناديل كلينكس",
        withMargin: 46.2,
        withSales: 0.18,
        noMargin: 43.1,
        noSales: 0.18,
      },
      {
        name: "ورق طباعة A4",
        withMargin: 42.8,
        withSales: 0.14,
        noMargin: 39.6,
        noSales: 0.13,
      },
      {
        name: "أكياس قمامة",
        withMargin: 44.6,
        withSales: 0.08,
        noMargin: 41.5,
        noSales: 0.08,
      },
    ],
  },
  {
    name: "مسطحات",
    withMargin: 33.22,
    withSales: 0.08,
    noMargin: 47.55,
    noSales: 0.23,
    products: [
      {
        name: "عصير برتقال طبيعي",
        withMargin: 34.1,
        withSales: 0.04,
        noMargin: 48.2,
        noSales: 0.12,
      },
      {
        name: "مياه معدنية 1.5L",
        withMargin: 32.3,
        withSales: 0.04,
        noMargin: 46.9,
        noSales: 0.11,
      },
    ],
  },
  {
    name: "غير مصنف 2",
    withMargin: 38.41,
    withSales: 0.88,
    noMargin: 21.4,
    noSales: 0.21,
    products: [
      {
        name: "منتج متنوع أ",
        withMargin: 39.5,
        withSales: 0.45,
        noMargin: 22.3,
        noSales: 0.11,
      },
      {
        name: "منتج متنوع ب",
        withMargin: 37.3,
        withSales: 0.43,
        noMargin: 20.5,
        noSales: 0.1,
      },
    ],
  },
  {
    name: "منتجات غذائية",
    withMargin: 27.75,
    withSales: 7.69,
    noMargin: 21.4,
    noSales: 0.21,
    products: [
      {
        name: "أرز عنبر 5كجم",
        withMargin: 29.4,
        withSales: 2.1,
        noMargin: 22.8,
        noSales: 0.06,
      },
      {
        name: "زيت نباتي 1.8L",
        withMargin: 26.8,
        withSales: 1.95,
        noMargin: 20.6,
        noSales: 0.05,
      },
      {
        name: "سكر أبيض 2كجم",
        withMargin: 27.1,
        withSales: 1.8,
        noMargin: 21.1,
        noSales: 0.04,
      },
      {
        name: "شاي ليبتون 100كيس",
        withMargin: 28.2,
        withSales: 1.84,
        noMargin: 21.1,
        noSales: 0.06,
      },
    ],
  },
  {
    name: "مستلزمات الأعمال",
    withMargin: 38.51,
    withSales: 0.15,
    noMargin: 21.4,
    noSales: 0.21,
    products: [
      {
        name: "ورق طباعة مكتبي",
        withMargin: 40.2,
        withSales: 0.08,
        noMargin: 22.5,
        noSales: 0.11,
      },
      {
        name: "أقلام حبر جاف",
        withMargin: 36.8,
        withSales: 0.07,
        noMargin: 20.3,
        noSales: 0.1,
      },
    ],
  },
  {
    name: "مسطحات غذائية",
    withMargin: 38.43,
    withSales: 3.24,
    noMargin: 21.4,
    noSales: 0.21,
    products: [
      {
        name: "عصير مانجو 1L",
        withMargin: 39.1,
        withSales: 1.2,
        noMargin: 22.1,
        noSales: 0.08,
      },
      {
        name: "مشروب ليمون 500مل",
        withMargin: 37.8,
        withSales: 1.04,
        noMargin: 20.8,
        noSales: 0.07,
      },
      {
        name: "ماء كوكاكولا 600مل",
        withMargin: 38.4,
        withSales: 1.0,
        noMargin: 21.3,
        noSales: 0.06,
      },
    ],
  },
];
